#!/usr/bin/env python

import os
import re
import sys


def print_tree(dirname, indent):
    filenames = os.listdir(dirname)
    filenames.sort()
    for filename in filenames:
        if filename.startswith('.'):
            continue
        fullname = os.path.join(dirname, filename)
        if os.path.isdir(fullname):
            print indent + filename
            print_tree(fullname, indent + '  ')
        else:
            print indent + filename


def main(argv):
    if len(argv) < 2:
        argv.append('.')
    print_tree(argv[1], '')


if __name__ == '__main__':
    main(sys.argv)
